/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/input-button/input-button";
import { CheckboxVariant } from "./components/input-checkbox/input-checkbox";
export namespace Components {
    interface InputButton {
        "href"?: string;
        "variant": ButtonVariant;
    }
    interface InputCheckbox {
        "checked": boolean;
        "variant": CheckboxVariant;
    }
    interface ThemeRoot {
        "background": string;
        "error": string;
        "inline": boolean;
        "primary": string;
        "secondary": string | undefined;
        "tertiary": string | undefined;
    }
}
declare global {
    interface HTMLInputButtonElement extends Components.InputButton, HTMLStencilElement {
    }
    var HTMLInputButtonElement: {
        prototype: HTMLInputButtonElement;
        new (): HTMLInputButtonElement;
    };
    interface HTMLInputCheckboxElement extends Components.InputCheckbox, HTMLStencilElement {
    }
    var HTMLInputCheckboxElement: {
        prototype: HTMLInputCheckboxElement;
        new (): HTMLInputCheckboxElement;
    };
    interface HTMLThemeRootElement extends Components.ThemeRoot, HTMLStencilElement {
    }
    var HTMLThemeRootElement: {
        prototype: HTMLThemeRootElement;
        new (): HTMLThemeRootElement;
    };
    interface HTMLElementTagNameMap {
        "input-button": HTMLInputButtonElement;
        "input-checkbox": HTMLInputCheckboxElement;
        "theme-root": HTMLThemeRootElement;
    }
}
declare namespace LocalJSX {
    interface InputButton {
        "href"?: string;
        "variant"?: ButtonVariant;
    }
    interface InputCheckbox {
        "checked"?: boolean;
        "variant"?: CheckboxVariant;
    }
    interface ThemeRoot {
        "background"?: string;
        "error"?: string;
        "inline"?: boolean;
        "primary"?: string;
        "secondary"?: string | undefined;
        "tertiary"?: string | undefined;
    }
    interface IntrinsicElements {
        "input-button": InputButton;
        "input-checkbox": InputCheckbox;
        "theme-root": ThemeRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-button": LocalJSX.InputButton & JSXBase.HTMLAttributes<HTMLInputButtonElement>;
            "input-checkbox": LocalJSX.InputCheckbox & JSXBase.HTMLAttributes<HTMLInputCheckboxElement>;
            "theme-root": LocalJSX.ThemeRoot & JSXBase.HTMLAttributes<HTMLThemeRootElement>;
        }
    }
}
